# Generated by Django 3.1.4 on 2021-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210226_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='pos_left',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tile',
            name='pos_top',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
