# Generated by Django 3.1.4 on 2021-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last',
        ),
        migrations.AddField(
            model_name='tile',
            name='last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='last_left',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tile',
            name='last_top',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
